# Generated by Django 4.2.8 on 2024-01-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=120)),
                ('assunto', models.TextField(default='Entre em contato comigo!')),
            ],
        ),
    ]
