# Generated by Django 5.0 on 2023-12-26 12:53

import django.db.models.deletion
import projetos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_1', models.ImageField(blank=True, null=True, upload_to=projetos.models.upload_path)),
                ('imagem_2', models.ImageField(blank=True, null=True, upload_to=projetos.models.upload_path)),
                ('imagem_3', models.ImageField(blank=True, null=True, upload_to=projetos.models.upload_path)),
                ('imagem_4', models.ImageField(blank=True, null=True, upload_to=projetos.models.upload_path)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=50)),
                ('sobre', models.CharField(max_length=350)),
                ('imagem_cliente', models.ImageField(blank=True, null=True, upload_to=projetos.models.upload_path)),
                ('feedback', models.CharField(max_length=150)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('visivel', models.BooleanField(default=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.cidade')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
