# Generated by Django 5.0 on 2024-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', max_length=20),
        ),
    ]
