# Generated by Django 5.0 on 2024-01-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projetos_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetos',
            old_name='imagem_1',
            new_name='miniatura',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='imagem_2',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='imagem_3',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='imagem_4',
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
