# Generated by Django 5.0 on 2024-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_rename_imagem_1_projetos_miniatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
