# Generated by Django 5.0 on 2024-01-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_projetos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='servicos_realizados',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
