# Generated by Django 5.0 on 2024-01-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_projetos_servicos_realizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
    ]
