# Generated by Django 5.0 on 2024-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_projetos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
