# Generated by Django 5.0 on 2024-01-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_alter_projetos_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='sobre',
        ),
    ]
