# Generated by Django 5.0 on 2024-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_remove_projetos_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
