# Generated by Django 4.2.8 on 2023-12-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0002_alter_carrossel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrossel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='globa/images/carrossel-imgs/%y/%m/'),
        ),
    ]
