# Generated by Django 5.0 on 2023-12-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0008_alter_carrossel_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrossel',
            old_name='descricao',
            new_name='descricao_carrossel',
        ),
        migrations.RenameField(
            model_name='carrossel',
            old_name='titulo',
            new_name='titulo_carrossel',
        ),
        migrations.RemoveField(
            model_name='carrossel',
            name='imagem',
        ),
        migrations.CreateModel(
            name='ImagemCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='carrossel-imgs/%y/%m/')),
                ('titulo_imagem', models.CharField(max_length=100)),
                ('descricao_imagem', models.CharField(blank=True, max_length=50, null=True)),
                ('carrossel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrossel.carrossel')),
            ],
            options={
                'verbose_name_plural': 'imagens_carrossel',
            },
        ),
    ]
