# Generated by Django 5.0 on 2023-12-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0009_rename_descricao_carrossel_descricao_carrossel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemcarrossel',
            options={'verbose_name_plural': 'imagens dos carrosseis'},
        ),
        migrations.RemoveField(
            model_name='carrossel',
            name='descricao_carrossel',
        ),
    ]
