# Generated by Django 5.0 on 2023-12-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0010_alter_imagemcarrossel_options_and_more'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrossel',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projetos'),
        ),
    ]
