# Generated by Django 5.0 on 2023-12-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0011_carrossel_servico'),
        ('servicos', '0004_servicos_visivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrossel',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servicos'),
        ),
    ]
