# Generated by Django 5.0 on 2023-12-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0012_alter_carrossel_servico'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrossel',
            name='Projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projetos'),
        ),
    ]
