# Generated by Django 5.0 on 2023-12-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0014_rename_projeto_carrossel_projeto_and_more'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrossel',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projetos'),
        ),
    ]
