# Generated by Django 5.0 on 2023-12-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0016_carrossel_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrossel',
            name='home',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
