# Generated by Django 5.0 on 2024-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0017_alter_carrossel_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemcarrossel',
            name='imagem',
            field=models.ImageField(upload_to='carrossel-imgs/%y/%m/'),
        ),
    ]
