# Generated by Django 5.0 on 2024-02-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0018_alter_imagemcarrossel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrossel',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
