# Generated by Django 4.2.8 on 2024-01-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name_plural': 'Postagens'},
        ),
    ]
