# Generated by Django 4.2.8 on 2023-12-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos-imgs/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
