# Generated by Django 4.2.8 on 2023-12-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name_plural': 'Servicos'},
        ),
        migrations.AlterField(
            model_name='servicos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos-imgs/<django.db.models.fields.CharField>/'),
        ),
    ]
